name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      # Execute unit and instrumented tests
    - name: Unit Test with Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.14.3
      with: 
          api-level: 29
          script: ./gradlew connectedCheck 

      # run: ./gradlew testDebugUnitTest

    - name: generate report
      uses: actions/upload-artifact@v2
      with:
        name: report 
        path: app/build/reports/coverage/androidTest


    - name: Download Test Reports Folder
      uses: actions/download-artifact@v2
      with:
        name: report
        path: app/build/reports/coverage/androidTest

    - name: Upload Test Report
      run:  bash <(curl -s https://codecov.io/bash) -f "app/build/reports/coverage/androidTest/debug/report.xml"
